#!/usr/bin/env python3
"""
Property-based tests for nginx configuration generation.
"""

import re
import subprocess
import tempfile
from hypothesis import given, strategies as st, settings


def generate_nginx_config(domain: str, port: int, username: str) -> str:
    """
    Generate nginx configuration for an application.
    
    This simulates the nginx config generation from setup-application.sh
    """
    config = f"""# Nginx configuration for {domain}
# Generated by setup-application.sh

# Redirect www to non-www
server {{
    listen 80;
    listen 443 ssl http2;
    server_name www.{domain};
    
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    
    return 301 https://{domain}$request_uri;
}}

# HTTP to HTTPS redirect
server {{
    listen 80;
    server_name {domain};
    
    return 301 https://$server_name$request_uri;
}}

# Main HTTPS server block
server {{
    listen 443 ssl http2;
    server_name {domain};
    
    # SSL configuration
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    
    # SSL security settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    
    # Static files location
    location /static {{
        alias /home/{username}/app/static;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}
    
    # Proxy to application
    location / {{
        proxy_pass http://localhost:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support (if needed)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }}
}}
"""
    return config


@settings(max_examples=100)
@given(st.integers(min_value=1024, max_value=65535))
def test_nginx_config_contains_correct_proxy_pass(port):
    """
    Property 2: Nginx proxy configuration
    
    For any application port number, when nginx configuration is generated,
    the configuration should contain a proxy_pass directive pointing to
    localhost with that port number.
    
    """
    domain = "example.com"
    username = "example"
    
    config = generate_nginx_config(domain, port, username)
    
    # The config should contain proxy_pass to the specified port
    expected_proxy_pass = f"proxy_pass http://localhost:{port};"
    assert expected_proxy_pass in config, \
        f"Config does not contain expected proxy_pass directive: {expected_proxy_pass}"
    
    # Verify it's in a location block
    assert "location /" in config, \
        "Config should contain a location / block"
    
    # Verify the config has server blocks
    assert "server {" in config, \
        "Config should contain server blocks"
    
    # Verify SSL configuration is present
    assert "listen 443 ssl" in config, \
        "Config should contain HTTPS listener"


@settings(max_examples=100)
@given(
    st.text(alphabet='abcdefghijklmnopqrstuvwxyz0123456789.-', min_size=3, max_size=50),
    st.integers(min_value=1024, max_value=65535)
)
def test_nginx_config_structure_is_valid(domain, port):
    """
    Property: Generated nginx config should have valid structure.
    
    For any domain and port, the generated config should contain
    all required nginx directives and blocks.
    """
    # Sanitize domain to create username
    import hashlib
    sanitized = re.sub(r'[^a-z0-9]', '', domain.lower())
    hash_suffix = hashlib.md5(domain.encode()).hexdigest()[:6]
    max_base_len = 26
    if len(sanitized) > max_base_len:
        sanitized = sanitized[:max_base_len]
    username = sanitized + hash_suffix
    
    if not username:  # Skip if username is empty
        return
    
    config = generate_nginx_config(domain, port, username)
    
    # Count server blocks (should have 3: www redirect, http redirect, main https)
    server_count = config.count("server {")
    assert server_count == 3, \
        f"Config should contain exactly 3 server blocks, found {server_count}"
    
    # Verify SSL certificate paths reference the domain
    assert f"/etc/letsencrypt/live/{domain}/fullchain.pem" in config, \
        "Config should reference SSL certificate for domain"
    
    # Verify static files path references the username
    assert f"/home/{username}/app/static" in config, \
        "Config should reference static files path for user"
    
    # Verify proxy_pass is present
    assert f"proxy_pass http://localhost:{port}" in config, \
        "Config should contain proxy_pass directive"


@settings(max_examples=100)
@given(st.integers(min_value=1024, max_value=65535))
def test_nginx_config_has_required_proxy_headers(port):
    """
    Property: Nginx config should set required proxy headers.
    
    For any port, the generated config should include standard
    proxy headers for proper request forwarding.
    """
    domain = "test.example.com"
    username = "testexample"
    
    config = generate_nginx_config(domain, port, username)
    
    # Check for required proxy headers
    required_headers = [
        "proxy_set_header Host",
        "proxy_set_header X-Real-IP",
        "proxy_set_header X-Forwarded-For",
        "proxy_set_header X-Forwarded-Proto"
    ]
    
    for header in required_headers:
        assert header in config, \
            f"Config should contain proxy header: {header}"


if __name__ == '__main__':
    import pytest
    import sys
    
    # Run the tests
    sys.exit(pytest.main([__file__, '-v']))
